version: '3'
services:
  server:
    container_name: node-v12
    image: node:12

    volumes:
      - .:/usr/src/service/
    working_dir: /usr/src/service/
    ports:
      - 3000:3000
    command:
      sh -c 'npm ci && npm start'
  dbmain:
    container_name: db-main-ps
    image: postgres:9.6.2-alpine
    environment:
      POSTGRES_USER: main
      POSTGRES_DB: main
      POSTGRES_PASSWORD: main
    ports:
      - 54321:5432
    volumes:
      - ./data:/var/lib/postgresql/data


